#!/bin/sh
cat << EOF > /tmp/audio.c
#include <math.h>
#include <stdio.h>
main() {
  long int t;
  int sample;
  for(t=0;;t++) {
    sample = (
EOF
cat $1 >> /tmp/audio.c
cat << EOF >> /tmp/audio.c
    );
    fputc(sample, stdout);
  }
}
EOF

mkfifo /tmp/pipe1 /tmp/pipe2 2>/dev/null

hexdump -Cv < /tmp/pipe1 &
cat /tmp/pipe2 | aplay -r 8000 -f U8 2>/dev/null &

gcc -lm /tmp/audio.c -o /tmp/audio && /tmp/audio | pv -qL 8000 | tee /tmp/pipe1 > /tmp/pipe2
